/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.nsu.ccfit.gerasimov2.a;

import org.junit.Test;
import static org.junit.Assert.*;

public class GameTest {
    @Test public void appHasAGreeting() {
        Game classUnderTest = new Game();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
