# Every gem is represented by 2 properties: Gem itself and GemDestroyer that readlises logic of destroying this kind of Gem.

Match3=ru/nsu/ccfit/gerasimov2/a/gem/Match3Gem
Match3Destroyer=ru/nsu/ccfit/gerasimov2/a/gem/Match3GemDestroyer.java

