/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.nsu.ccfit.gerasimov2.a.game;

public class App {

    public static void main(String[] args) {
        ConsoleController controller = new ConsoleController();
        controller.runGame();
    }
}
